#!/usr/bin/env bash
# Fetches deploy secrets from 1Password into a local, gitignored .env
# Usage: ./scripts/fetch-secrets.sh
# Requires: op CLI signed in (op signin), and items named below in your vault.
set -euo pipefail

ENV_FILE="$(dirname "$0")/../.env"
ACCOUNT="${OP_ACCOUNT:-}"   # set if you have multiple 1P accounts

OP() {
  if [ -n "$ACCOUNT" ]; then command op --account "$ACCOUNT" "$@"; else command op "$@"; fi
}

# Ensure signed in
if ! OP whoami >/dev/null 2>&1; then
  echo "Signing in to 1Password (follow the prompt)..."
  if [ -n "$ACCOUNT" ]; then op signin --account "$ACCOUNT"; else op signin; fi
fi

# Resolve item reference → field value. Tries: field by label, then credential,
# then a generic 'value'. Edit names to match your vault.
get() {
  local item="$1"; local field="${2:-credential}"
  local val
  val="$(OP item get "$item" --fields "$field" 2>/dev/null || true)"
  if [ -z "$val" ]; then val="$(OP item get "$item" --fields value 2>/dev/null || true)"; fi
  if [ -z "$val" ]; then val="$(OP item get "$item" --reveal 2>/dev/null | awk -F'[][]' '/value/{print; exit}' || true)"; fi
  echo "$val"
}

GITHUB_TOKEN="$(get 'GitHub Token')"
COOLIFY_TOKEN="$(get 'Coolify Token')"
COOLIFY_BASE_URL="${COOLIFY_BASE_URL:-https://cool.neima.me}"

{
  echo "# Auto-generated by scripts/fetch-secrets.sh — DO NOT COMMIT"
  echo "GITHUB_TOKEN=$GITHUB_TOKEN"
  echo "COOLIFY_TOKEN=$COOLIFY_TOKEN"
  echo "COOLIFY_BASE_URL=$COOLIFY_BASE_URL"
  echo "DEPLOY_DOMAIN=duke.neima.me"
} > "$ENV_FILE"

echo "Wrote $ENV_FILE"
echo "  GITHUB_TOKEN: ${GITHUB_TOKEN:+set}${GITHUB_TOKEN:-MISSING}"
echo "  COOLIFY_TOKEN: ${COOLIFY_TOKEN:+set}${COOLIFY_TOKEN:-MISSING}"
